alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias ......='cd ../../../../../'

alias v='vim'
alias his='history | grep $1'
alias tmux='tmux -2'
alias h2d='printf "%d\\n" $1'
alias fperm='stat -c "%a %n" $1'
